### ISSUE TITLE
Can This program have more features

### ISSUE THREAD

**Issue by Bhavya0304** [kingap7/python-password-generator-and-saver#1]
If I have many passwords can this program have a feature of also searching my password according to the media I have provided (also the search algorithm used should not be linear search but some efficient search algorithm) also what if I want my password to follow a pattern like (minimum 8 length or at least one '@' or at least on number) can't I have feature of choosing password my way a little

**Comment by kingap7** [comment]
Yeah it is possible to do
You can Search password by there username or how you save it
But I am not working on this program anymore because it was my practice program so if you're interested in doing that you can contribute..
Thanks
